version: '3.8'

services:
  app:
    build: .
    container_name: laravel_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: esports
      DB_USERNAME: root
      DB_PASSWORD: ""
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"  # permite senha vazia
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: esports
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
